var _frame_jobs_8cs =
[
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs", "class_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs.html", "class_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.FrameCleanupJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_frame_cleanup_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_frame_cleanup_job" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.StartUpAlignJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_start_up_align_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_start_up_align_job" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.RollProfileJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_roll_profile_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_roll_profile_job" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.RollRateLimiterJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_roll_rate_limiter_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_roll_rate_limiter_job" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.JointEndToStartBlendJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_joint_end_to_start_blend_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_joint_end_to_start_blend_job" ],
    [ "TrackFlowPro.Runtime.Core.Kernels.FrameJobs.RMFSmootherJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_r_m_f_smoother_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_frame_jobs_1_1_r_m_f_smoother_job" ]
];