var _polyline_build_curvature_samples_job_8cs =
[
    [ "TrackFlowPro.Runtime.Core.Kernels.PolylineBuildCurvatureSamplesJob", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_polyline_build_curvature_samples_job.html", "struct_track_flow_pro_1_1_runtime_1_1_core_1_1_kernels_1_1_polyline_build_curvature_samples_job" ]
];